name: Weekly Awards Predictions

on:
  schedule:
    - cron: "0 14 * * 4"    # Thursdays 14:00 UTC (~6–7am PT depending on DST)
  workflow_dispatch: {}     # allow manual run from Actions tab

permissions:
  contents: write           # allow committing outputs back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run weekly prediction
        run: python run_weekly.py

      - name: Commit results
        run: |
          git config user.name "${{ github.actor }}-bot"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add predictions/
          if ! git diff --staged --quiet; then
            git commit -m "Weekly update: predictions"
            git push
          else
            echo "No changes to commit."
          fi
